### ISSUE TITLE
Add internationalisation

### ISSUE THREAD

**Issue by markachten** [thtm88/pubquiz#14]
Using https://kazupon.github.io/vue-i18n/

**Comment by markachten** [comment]
Requires translating backend messages as well

**Comment by tjeerdhans** [comment]
I was thinking that another option could be to consolidate all resultcodes (error as well as success codes) into a ResultCode enum. That would avoid clashes, and we could still just transmit the ints over the line.
But, in second thought, I think your solution is better. It's conceptually clearer to keep the error codes separate, and the use of the strings in the response messages doesn't result in proportionally very larger messages.
I think we should put the SuccessCodes under PubQuiz.Domain as well.

**Comment by markachten** [comment]
Nice. Would that require refactoring the backend code as well?

**Comment by tjeerdhans** [comment]
Yup.
